### ISSUE TITLE
Possible error in `GetShortestPath`

### ISSUE THREAD

**Issue by F2** [viceroypenguin/SuperLinq#126]
I was using `GetShortestPath` for a certain online Christmas challenge, but it was returning unstable results. After switching to QuikGraph, my code worked great. Either I am using `GetShortestPath` wrong, or it has a bug. Could you help looking into it?

Here is an xUnit test demonstrating the error. It constructs a graph, shuffles the outgoing nodes, and computes the shortest distance from **AA** to **UM**. It can easily be seen that going through **QT**, the shortest distance is **3**. However, it yields distances such as 6, 9 and 14 (and also 3).

```csharp
using QuikGraph;
using QuikGraph.Algorithms;
using SuperLinq;
using Xunit;

namespace AdventOfCode.Tests;

public class GraphTests
{
    class Valve
    {
        public string Name { get; init; }
        public Valve[] Next { get; set; }
    }

    [Fact]
    public void Test()
    {
        var data = """
            EJ => MC
            WC => OW, RU
            NP => VR, KL
            AA => QT, AP, EZ, AK, XV
            VO => KM, RF, HS, LJ, IA
            CB => UI, UP
            TE => JT
            CZ => UP, OW
            LJ => DV, VO
            UP => SK, CB, CZ
            FP => OW, RE
            KM => SE, VO
            DV => LJ, UM
            FL => AH, TS
            VR => DM, TF, NP
            IA => VS, VO
            RF => VO, JF
            RT => UM, SE
            RU => AR, WC
            SE => GU, KM, CX, RT
            MC => EJ, AR
            TF => AH, VR
            CX => SE, TO
            GL => UY, KL, CY
            GU => SE, EZ
            VS => XN, IA
            EZ => AA, GU
            GK => FI, HZ
            JT => TE, XN
            DM => VR, HZ
            AR => UI, RU, MC
            XN => XP, JT, VS, GT, CY
            CY => XN, GL
            QT => UM, AA
            KL => GL, NP
            SK => XV, UP
            OW => CZ, WC, FP
            AK => AA, HS
            XV => AA, SK
            GT => XN, UM
            FI => JF, GK
            UY => JF, GL
            UM => DV, GT, RT, QT
            IQ => HZ, AH
            JF => RF, FI, UY, RE, TS
            TS => JF, FL
            AH => IQ, FL, TF
            HS => AK, VO
            HZ => IQ, DM, GK
            TO => CX
            XP => AP, XN
            AP => XP, AA
            RE => JF, FP
            UI => AR, CB
            """;

        var lines = data.Trim().Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
        var nodes = new Dictionary<string, Valve>();

        // Create vertices
        foreach (var line in lines)
        {
            var name = line.Split(" => ")[0];
            nodes.Add(name, new Valve { Name = name });
        }

        // Create edges
        foreach (var line in lines)
        {
            var name = line.Split(" => ")[0];
            var outNodesNames = line.Split(" => ")[1].Split(", ");
            var outNodes = outNodesNames.Select(outName => nodes[outName]).ToArray();
            nodes[name].Next = outNodes;
        }

        // Compute shortest path a few times
        for (var i = 0; i < 1000; i++)
        {
            foreach (var node in nodes.Values)
            {
                node.Next = node.Next.RandomSubset(node.Next.Length).ToArray();
            }

            // Expect AA -> QT -> UM
            Assert.Equal(3, SuperEnumerable.GetShortestPath<Valve, int>(
                nodes["AA"], 
                (v, c) => v.Next.Select(n => (n, 1)),
                nodes["UM"]
            ).Count());
        }
    }
}
```

**Comment by viceroypenguin** [comment]
Initial thoughts: `GetShortestPath` relies an `IEqualityComparer<TState>`. If one is not provided, then it uses `EqualityComparer<TState>.Default`. If a `class` does not provide one, then it uses `ReferenceEqual`. I'm guessing (though not yet proven) that this is creating the problem here. You could update `Valve` to be `IEquatable<Valve>` and override `.Equals()` and `.GetHashCode()`; all three of which can defer to the value from `Name`, since that's the part that's relevant for a node.

**Comment by viceroypenguin** [comment]
Two things:
1. `GetShortestPath` relies an `IEqualityComparer<TState>`. If one is not provided, then it uses `EqualityComparer<TState>.Default`. If a `class` does not provide one, then it uses `ReferenceEqual`. I'm guessing (though not yet proven) that this is creating the problem here. You could update `Valve` to be `IEquatable<Valve>` and override `.Equals()` and `.GetHashCode()`; all three of which can defer to the value from `Name`, since that's the part that's relevant for a node. This is likely not an issue here, since the same references are returned every time (so equality should be correct), but may be an issue with other classes. `record`s are better, but only if they comprise the entire state.
2. The real issue here: you're doing `.Select(n => (n, 1))`, when it should be `.Select(n => (n, 1 + c))`. In order to abstract the cost (`TCost`), and since this supports before `INumber<>` was introduced in .net 7, I rely on the `getNeighbors` function to run the additions. You can see my use of it to do the same thing [here](https://github.com/viceroypenguin/adventofcode/blob/9a87e57ebd172c9df654bf0ffa81690a94a79fe2/AdventOfCode.Puzzles/2022/day16.original.cs#L53). Maybe I did not address this clearly enough in the docs - if you can, please help me on how to improve this area of the documentations.

**Comment by F2** [comment]
Indeed, `.Select(n => (n, 1))` solves my issue. Thanks for the quick response! :)

I was using [QuikGraph](https://github.com/KeRNeLith/QuikGraph/wiki/Dijkstra-Shortest-Distance-Example) previously, where you only have to provide the cost of the edge:
```
Func<TEdge, double> edgeCost = edge => 1;
```
That confused me. Now I know. 👍

**Comment by viceroypenguin** [comment]
Glad I could help. And looks like QuikGraph went the other possible solution - fixing the type of the cost as `double`. This means they can do the addition instead of making the consumer do it.

If I didn't support pre-7.0 I might update to INumber and do the addition, but alas...
