### ISSUE TITLE
Batch/Chunk operator with overlap

### ISSUE THREAD

**Issue by matyasbach** [viceroypenguin/SuperLinq#474]
@viceroypenguin Thank you for the answer in https://github.com/morelinq/MoreLINQ/discussions/1005

Currently there is missing nice discoverable method for batching with some overlap.
E.g.
```
[1,2,3,4,5,6].Chunk/Batch(count: 3, overlap: 1) => [[1,2,3], [3,4,5], [5,6]]
```

`Buffer(count: 3, skip: 2)` works but seems unintuitive and a bit like leaking implementation (why Buffer? what is skipped? Doc must be read to understand it).

So this is proposal for _Batch_ method overload and prefferably even for _Chunk_ method as it would be nice overload for System.Linq.Chunk().

What do you think?

**Comment by viceroypenguin** [comment]
I agree that `Buffer` is not the best name; it is copied from System.Interactive. 

However, the `skip` parameter seems valid to me - it allows for skips that are less _or more_ than `count`. This would work if you wanted batches that allow for space between the batches (`[1,2,3,4,5,6].Buffer(count: 3, skip: 4) => [[1,2,3], [5, 6]]`). The `overlap` parameter does not allow for this possibility semantically.

I'm open to adding `Batch` and/or `Chunk` overloads that proxy the `Buffer` version in order to have consistency between the three operator names, but I'd like to discuss further on the parameters. Thoughts?

**Comment by matyasbach** [comment]
I understand you wanted to keep the same syntax as in System.Interactive and it's great that it allows space between batches.
But I'd expect this:
`[1,2,3,4,5,6].Buffer(count: 3, skip: 1) => [[1,2,3], [5,6]]`

That's why the name `skip` might be misleading.

And it's value is dependent on `count` value. Let's say you want batches of 3 elements with skipping 1 element in between -> now: `x.Buffer(3, 4)` then you decide batches should have 5 elements and you need to change both parameters: `x.Buffer(5, 6)`. (And code doesn't really follow english sentence).

So IMO `overlap` in `Batch/Chunk` methods seems more intuitive and `Buffer` could still be proxied inside (`skip = count - overlap`).
`overlap` could be <0 to allow for spaces between batches.

**Comment by viceroypenguin** [comment]
Thought experiment: how do you provide for both `overlap` and `skip`? For example, if you try to provide `Batch(int count, int overlap)`, you prevent the possibility of using `Batch(int count, int skip)`, because C# will not allow overloads with the same types but different names. 

The current parameters in `Buffer` may not be as intuitive `count` perspective, but it is general enough to allow reading and processing both `overlap` and `skip` in the same method. All it takes is imagining `skip` from the iteration perspective rather than the `count` perspective. Which, to be honest, is how I tend to read any parameters anyway. To me, `skip` and `overlap` should not operate on `count`, but on `source`. 

To do this otherwise would require `BatchOverlap` and `BatchSkip`, which clutters the intellisense and increases maintenance cost (more methods to cover).

**Comment by matyasbach** [comment]
I think I was too narrow-sighted about `Buffer` when thinking about it as a chunking method. Now it's name and parameter `skip` (both it's name and behavior) make sense to me. And it has probably many other use-cases.

However it's not intuitive to use for chunking _source_ with or without skipping/overlapping elements.

So with these variants I see these problems:
- `Batch(int count, int skip)`
  - what's the behavior/perspective of `skip`?

- `Batch(int count, int overlap)`
  + seems clear (IMO)
  + still allows _skipping_ elements by setting negative value

- `Batch(int count, int every)`
  - from this `Batch(count: 3, every: 2)` I'd probably expect behavior like `Batch(3).TakeEvery(2)` or `Batch(3).Select(b => b.TakeEvery(2))` (unclear on first sight)

All of these would block `Batch(int count, int somethingElse)`.

> To do this otherwise would require BatchOverlap and BatchSkip, which clutters the intellisense and increases maintenance cost (more methods to cover).

I agree it's probably not the way.

Maybe `Window` method could be overloaded with `skip/overlap/every` but there are probably the same things to consider.

**Comment by viceroypenguin** [comment]
Given the level of ambiguity at this point, I'm inclined to close the issue for now. If you have an idea of what you would like to see, please feel free to re-open the issue and share your thoughts!

**Comment by matyasbach** [comment]
Ok, thanks for considering and discusing it.
