### ISSUE TITLE
Reliance on https://github.com/dotnet/reactive - is this good?  is this temporary?

### ISSUE THREAD

**Issue by Bellarmine-Head** [viceroypenguin/SuperLinq#50]
Newbie question...

I've recently started to work with `IAsyncEnumerable<T>`, and found the lack of `ToListAsync`, `SelectAsync`, `FirstOrDefaultAsync` etc. in official .NET 6 a little surprising.

I then looked into `System.Linq.Async` via https://github.com/dotnet/reactive and found it quite impenetrable, and ended up writing my own, simple `ToListAsync` method to satisfy my immediate, simple needs.

Mark Heath's excellent [article](https://markheath.net/post/async-enumerable-2) then helped me understand `System.Linq.Async` a lot better, so I might use that package next time.  But I also saw a link to this repo, which initially looked promising re. providing async versions of familiar LINQ methods.  And there's [documentation](https://github.com/viceroypenguin/SuperLinq/blob/master/Source/SuperLinq.Async/readme.md)!

But... the docs don't include  `ToListAsync`, `SelectAsync`, `FirstOrDefaultAsync` etc.  How could this be?

Then I found...

```
<PackageReference Include="System.Interactive.Async" Version="6.0.1" />
<PackageReference Include="System.Linq.Async" Version="6.0.1" />
```

:-) 

I wonder if this reliance on https://github.com/dotnet/reactive is a good thing...  Perhaps it's just a temporary thing(?)  It seems to me that we are now reliant on another package, with its own issues (bugs, lack of docs).

In the fullness of time it might be nice if `SuperLinq` was a one-stop shop, in charge of its own destiny, without the `reactive` dependency.

If the `reactive` dependency is likely to continue for a while, should this be signposted on the front page of the repo?

**Comment by viceroypenguin** [comment]
Hey @Bellarmine-Head, thanks for reaching out! 

Yes, the reliance on dotnet/reactive will stay. There is some overlap between what SuperLinq(.Async) is doing and what System.Interactive(.Async) is doing; in order to avoid conflicts, it is better to rely on their methods than to duplicate methods. I generally prefer to work in a cooperative fashion than an either-or fashion, and creating a conflict between .SelectAsync() in their library and .SelectAsync() in this library would force an either-or.

Also, no reason to re-invent the wheel writing from scratch code that they've already written. 

Adding a notice of reliance on the docs page is a good idea though. Thanks for the suggestion. I'll add it soon.

**Comment by Bellarmine-Head** [comment]
@viceroypenguin - thanks for the clarifications.
