### ISSUE TITLE
MaxElementsBy removal

### ISSUE THREAD

**Issue by bradleypatton** [viceroypenguin/SuperLinq#61]
I updated to the latest package and see MaxElementsBy has been removed. In the doc I see that the recommended method to use instead is PartialSortBy but no example is provided. 

I want to return all of the items that share the maximum count (there can be more than one and I don't want to set a limit). So before I had code like:

`var maxItems = items.MaxElementsBy(item => item.Value);`

So now it looks like the code should be like the following to achieve the same results:

`var maxItems = items.PartialSortBy(int.MaxValue, (item) => item.Value);`

I switched to this package from MoreLinq as I agree with the idea of deprecating Linq methods that the common library adds. But in this case the base method has different functionality (`MaxBy` only returns one item). `PartialSortBy` with `int.MaxValue` was not intuitive to figure out but if it works the same I guess I will use it

**Comment by bradleypatton** [comment]
Actually I realize that `PartialSortBy` with `int.MaxValue` will just return all of the items in order. Is there a replacement way to get all of the items which share the max value?

**Comment by viceroypenguin** [comment]
Thanks for the insight. I had not considered that multiple equivalent values would be part of the `.MaxElementsBy()` usefulness. 

An easy workaround would be `item.DenseRankBy(item => item.Value).Where(r => r.rank == 1).Select(r => r.item);`. It would not be as performant (since it would require a full sort and a full pass to find the `rank == 1` items.

Would you mind if I rewrite the title of this issue to suggest adding `.DensePartialSortBy()`? This method would replicate that specific behavior of `.MaxElementsBy()` since you could select `.DensePartialSortBy(item => item.value, 1)`, which would return all elements of the first rank without sorting any further.  Thoughts?

**Comment by bradleypatton** [comment]
Just realized that I had not responded to this. Thanks for your reply and implementing a new solution. I ended up implementing a workaround for now but will take a look at the new method. 

Just some initial feedback. As far as names goes though `DensePartialSort` does not seem to be clear about what the function does or how I would go about discovering that if I was a new user. When I'm thinking about picking out objects that match a max (or min) value I'm not thinking about sorting (although internally it might be doing something like that).

**Comment by viceroypenguin** [comment]
I was just getting ready to release v4.3.0 including `DensePartialSort()` - managed to stop it in time... :) I chose the name specifically keying off the existing difference between `Rank()` and `DenseRank()`. If you have a better alternative, I'm open to suggestions.

**Comment by bradleypatton** [comment]
I called my internal method `MaxElementsBy` because that actually matched my expectations. The `By` is probably not even needed so `MaxElements` would indicate to me that it would look for the Max and return multiple elements. I have to run right now but will try and spend more time on this tomorrow. Thanks

**Comment by MisinformedDNA** [comment]
I don't know what `DenseRank()` means either, lol, but the reason you created `MaxElementsBy()` was to replace MoreLinq's `MaxBy()`, so I'm curious why you want to remove it?

NOTE: I just barely discovered this library due to MoreLinq collisions.

**Comment by viceroypenguin** [comment]
@MisinformedDNA To answer your specific question: MoreLinq originally had both `.MaxBy()` and `.PartialSort()`. When I first started trying to address MoreLinq's issues with the latest versions of .net, I simply renamed `.MaxBy()` to `.MaxElementsBy()` so that it wouldn't conflict with the new `.MaxBy()` in .net. 

When I actually started reviewing the code, in order to take ownership of a fork, I realized that the `.MaxElementsBy()` was using a poor algorithm and was essentially the same thing as `.PartialSort()`/`.PartialSortBy()`, I deleted the `.MaxElementsBy()` as being duplicate work.

What I missed in my review of `.MaxElementsBy()` was the possibility of returning all items at the same rank. This is why I wrote #62 to implement a method that would replace the missing functionality.

@MisinformedDNA and @bradleypatton - `.PartialSort()` existed previously in MoreLinq, and I have improved it. It exists because finding the K min/max elements of a sequence is faster than sorting the entire sequence ( $O(N \log K)$ instead of $O(N \log N)$ ). My reasoning (however incorrect) behind choosing `.DensePartialSort()` is the following: Assume you have a sequence (`var n = new int[]{4,3,1,3};`). `PartialSort(2)` will extract the two smallest elements and return them (`n.PartialSort(2) == [1, 3]`). However, `DensePartialSort(2)` will count the number of equivalent values and return everything for each set (`n.PartialSort(2) == [1, 3, 3]`). This is equivalent to the behavior lost in `.MaxElementsBy()` (the rest already being implemented by `.PartialSort()`). 

I could reintroduce `.MaxElements()`/`.MinElements()` functions for easier searching. However, if possible, I'd rather use direct functions for "give me the `K` max elements" (`n.MaxBy().First()`) and "give me the `K` equivalent sets" (`n.MaxBy().Take(k)`). I don't like extra code for having an intermediate class to deal with the secondary calls to determine what the consumer wants.

Alternatively, I could simply introduce `.MaxElements()`/`.MinElements()` that only return all elements that share the same max/min value, with a reference in the remarks to `.PartialSort()`/`.DensePartialSort()` for more fancy extrema selection.

Any thoughts either of you are willing to provide on this would be helpful! Thank you!

**Comment by viceroypenguin** [comment]
Spending some more time reading the original code, I'm realizing that the original `.MaxBy()` actually worked the way I'm proposing the new `.MaxElements()` method to work. I'm going to add new `.MaxElements()` shortcut methods to handle this specific case.

**Comment by MisinformedDNA** [comment]
Sounds good. What would you think of `MaxItems()` instead? And would you have the `XXXBy()` variants as well?

**Comment by viceroypenguin** [comment]
`.MaxItems()` is good alternative to me. And yes, I'll provide the `XxxBy()` variants as well.

**Comment by viceroypenguin** [comment]
@MisinformedDNA / @bradleypatton - Please review PR #63 and see if this addresses correctly?

**Comment by viceroypenguin** [comment]
v4.3.0 is released including `.DensePartialSort()` and `.MinItems()`/`.MaxItems()`
