### ISSUE TITLE
Some methods missing explanations for why not implemented in async

### ISSUE THREAD

**Issue by Arithmomaniac** [viceroypenguin/SuperLinq#68]
For example:

https://github.com/viceroypenguin/SuperLinq/blob/f52cca2d303734b2455f7f5166f9c524e0c4517b/README.md?plain=1#L141-L146

These methods are not listed as obsolete in the sync versions; should there be backlog items for them?

**Comment by viceroypenguin** [comment]
Honestly, partly a wondering game if anyone would notice... ;) Also, there are several different comments, so I didn't want to add that many footnotes unless necessary. Would enjoy your thoughts after reading the below.

* `ToDataTable`: Not many people use `DataTable` anymore, there are better data structures and reflection has gotten good enough that most dynamic displays that query columns do so using reflection. Maybe `[Obsolete]` would be good here? 
* `ToDelimitedString`: No reason it couldn't be implemented, it just requires copying more generator code from the sync version to the async version, and I never got around to it. Could easily add an issue for this one and leave it open until someone actually comments on it (as done with other operators).
* `ToDictionary`, `ToLookup`: These are shortcut methods with little independent value. Most of the operators provided by (MoreLinq/)SuperLinq are fully featured to do something unique. `ToDictionary` and `ToLookup` are shortcuts to the fx `ToDictionary`/`ToLookup` for tuples or `KeyValuePair<,>`. I'll keep the existing ones because they don't hurt anything, I don't want to waste time or energy adding the async ones.
* `Trace`: Similar issue, it's just a shortcut to calling `Trace.WriteLine()` for every item. No real advantage vs writing the code directly as necessary.
* `Transpose`: I could implement this one, it would be similar to the System.Interactive version of `.Merge()`. Probably deserves an issue like `ToDelimitedString` and wait until someone cares enough for me to implement.

**Comment by Arithmomaniac** [comment]
1, 3, 4) Maybe just add a footnote explanation for "stale" ones that you don't plan to update. (I'd save `Obsolete` for ones that are bad to use and have replacements, instead of ones you simply don't intend to support.)
2, 5) Reasonable

What about the following?
- Cartesian
- Evaluate
- Flatten
- Fold
- FullGroupJoin
- Return
- Unfold

**Comment by viceroypenguin** [comment]
@Arithmomaniac footnotes or issues have been added for all not-implemented operators.
